steps:
  - label: ":linux: compile"
    key: compile
    plugins:
      - docker-compose#v5.3.0:
          run: compile
          config: .buildkite/docker-compose.yml
          shell: false
          command: ["bash", "-x", "/src/build-kernel.sh"]
    artifact_paths:
      - "system_info.txt"
