name: Linux kernel build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: System Information
      run: |
        ./record-system-info.sh

    - name: Download kernel
      run: |
        ./download-kernel.sh

    - name: Build kernel
      run: |
        ./build-kernel.sh

    - name: Archive compile time output
      uses: actions/upload-artifact@v4
      with:
        name: compile-time-output
        path: |
          compile_time_output.txt
          system_info.txt